apiVersion: 1

datasources:
  - name: Rust Local Metrics
    uid: rust-local-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: grafana_reader
    isDefault: true
    editable: false
    jsonData:
      version: InfluxQL
      dbName: rust-server-metrics
      httpMode: POST
      timeInterval: 1s
    secureJsonData:
      password: $INFLUXDB_READ_USER_PASSWORD
